---
apiVersion: v1
name: zero-downtime-kubernetes
version: 1.0.0
description: OTUS reddit application POST homework
home: https://github.com/czm41k/helm-charts/
maintainers:
name: zero-downtime-kubernetes
    email: etselikov@express42.com
appVersion: 1.0
...
